export const TIMETABLE_API_CONTRACTS = {
  v1: {
    base: '/lms/timetable',
    endpoints: {
      entries: '/entries/',
      entryDetail: (id: number) => `/entries/${id}/`,
      weekView: '/entries/week/',
      bellSchedules: '/bell-schedules/',
      bellScheduleDetail: (id: number) => `/bell-schedules/${id}/`,
      tieredPeriods: '/tiered-periods/',
      rooms: '/rooms/',
      subjectCodes: '/subject-codes/',
      conflicts: '/conflicts/',
      locate: (id: number) => `/locate/${id}/`,
    },
  },
  myTimetable: {
    student: '/lms/my-timetable/',
    teacher: '/academics/my-timetable/',
  },
} as const;

export const STANDARD_RESPONSE_CONTRACT = {
  TimetableEntry: {
    id: 'number',
    academic_term: 'number',
    day_of_week: 'number',
    day_name: 'string',
    tiered_period: 'number',
    period_name: 'string',
    period_sequence: 'number',
    period_start: 'string (HH:mm)',
    period_end: 'string (HH:mm)',
    year_group: 'number',
    year_group_name: 'string',
    teacher: 'number',
    teacher_name: 'string',
    subject: 'number',
    subject_code: 'string',
    subject_name: 'string',
    subject_category: 'string',
    room: 'number | null',
    room_detail: 'Room | null',
    is_practical: 'boolean',
    practical_rooms: 'string',
    raw_cell_code: 'string',
  },
  Room: {
    id: 'number',
    name: 'string',
    capacity: 'number | null',
    room_type: 'string',
    is_lab: 'boolean',
    building: 'string',
    floor: 'number | null',
    is_active: 'boolean',
    notes: 'string',
  },
  SubjectCode: {
    id: 'number',
    code: 'string',
    full_name: 'string',
    category: 'string',
    is_active: 'boolean',
  },
  BellSchedule: {
    id: 'number',
    name: 'string',
    tier: "'EYF' | 'KS1' | 'KS2' | 'KS3'",
    applies_on_days: 'number[]',
    is_active: 'boolean',
    period_count: 'number | undefined',
    year_levels: 'number[] | undefined',
    periods: 'TieredPeriod[] | undefined',
  },
  TieredPeriod: {
    id: 'number',
    schedule: 'number',
    name: 'string',
    sequence: 'number',
    start_time: 'string (HH:mm)',
    end_time: 'string (HH:mm)',
    duration_minutes: 'number',
    period_type: "'ACADEMIC' | 'INSTITUTIONAL' | 'BREAK' | 'TRANSITION'",
    institutional_block_type: 'string | null',
    is_assignable: 'boolean',
  },
  ConflictReport: {
    conflict_type: "'TEACHER' | 'YEAR_GROUP' | 'PROTECTED_BLOCK'",
    entry_a_id: 'number | null',
    entry_b_id: 'number | null',
    day_of_week: 'number',
    start_time: 'string (HH:mm)',
    end_time: 'string (HH:mm)',
    description: 'string',
    severity: "'ERROR' | 'WARNING'",
  },
  WeekViewResponse: {
    monday: 'TimetableEntry[]',
    tuesday: 'TimetableEntry[]',
    wednesday: 'TimetableEntry[]',
    thursday: 'TimetableEntry[]',
    friday: 'TimetableEntry[]',
  },
} as const;
